### ISSUE TITLE
[bug]: No spam protection on contact form

### ISSUE THREAD

**Issue by heyitsOK** [Carleton-Blueprint/carleton-blueprint.github.io#110]
### What happened?

# Expected behavior
The contact form should be protected from spammers and bots
This could be done with reCAPTCHA or possibly through resend

# Actual behaviour
The contact form is not protected and we can be spammed with up to 100 emails per day

### Version

0.0.1 (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by voidranjer** [comment]
- Additional requirement for this ticket: Re-enable Resend
