### ISSUE TITLE
[feat] Change `ACTIVATION_LABEL_ID` to `ACTIVATION_LABEL`

### ISSUE THREAD

**Issue by voidranjer** [Carleton-Blueprint/carleton-blueprint.github.io#127]
Instead of requiring users to dig through the GitHub debug panel to find their label id, use the **name** of the label instead.

Make sure to update the documentation "Installation" page in the "4. Configuring Bluebot" setup.

Some concerns:
- How do you handle duplicate names?

This is an experimental ask, if the task becomes non-trivial and very involved, contact the task requester and possibly consider a different approach (or even just sticking to the current behavior).

**Comment by Oopsiepoopsie** [comment]
Hello James, I have finished this change on my own local branch, I'm wondering if i should do a pull request to add it to the main repo? I'm not that familiar with the whole process when working on a team project, so please let me know what to do next. Thank you!
