### ISSUE TITLE
Horizontal scrollbar on homescreen

### ISSUE THREAD

**Issue by voidranjer** [Carleton-Blueprint/carleton-blueprint.github.io#44]
![image](https://github.com/user-attachments/assets/1c67f0a1-67a6-4e61-9438-63224c76ea12)

![image](https://github.com/user-attachments/assets/f3b21e65-a94d-4afa-9c99-346ad9c082de)

We should remove the excess overflow space in the y-direction on the home page

**Comment by Arunteja27** [comment]
Resovled in #34
