### ISSUE TITLE
Headings not aligned according to figma in home page

### ISSUE THREAD

**Issue by voidranjer** [Carleton-Blueprint/carleton-blueprint.github.io#45]
Actual:
![image](https://github.com/user-attachments/assets/f5f8efbc-fdd1-4f89-95b8-6c46d480b6b5)

Figma:
![image](https://github.com/user-attachments/assets/5af8e251-177c-4617-942c-08cc44f6d69d)

**Comment by Arunteja27** [comment]
Responsive design fixed by @Zhangjason308
