### ISSUE TITLE
Projects carousel on home page spacing

### ISSUE THREAD

**Issue by heyitsOK** [Carleton-Blueprint/carleton-blueprint.github.io#65]
at specifics widths the projects carousel has huge whitespace around each item in the carousel

![image](https://github.com/user-attachments/assets/723bdd72-fa1d-418f-bafd-5046f46ee89c)

**Comment by Zhangjason308** [comment]
pushed small changes to main by accident, changed the width handling. In small width, shows one card, medium shows two cards, and large + shows three cards. 
I can rollback changes if needed and open changes on a branch first.

**Comment by heyitsOK** [comment]
okay thanks jason it looks good. just make sure to make make a branch/PR next time.
